### ISSUE TITLE
Verb `’gyur` and `song` as copula?

### ISSUE THREAD

**Issue by samyorode** [tibetan-nlp/annotation-docs#11]
· Do we treat _‘gyur_ as a copula (“A becomes B”)? E. g. _byang chub sems dpa’ ... lkug par mi ’gyur_ "the Bodhisattva is not mute" (Ex. from _brGyad stong_-Sutra)

· If so, what about _song_ (Pf. of _‘gro_)? E. g. Mil 11b: _nga bu gcig por song ba_ “I was/became an only son”. Is it _nga_ = `arg1` and _bu_ = `obl:arg` of _song_ (=> _song_ no copula but kind of motion verb)? Or _nga_ = `arg1` of _bu_ and _song_ = `cop` of _bu_ (=> _song_ is copula)?

**Comment by heacu** [comment]
Is the guidance at http://universaldependencies.org/u/dep/cop.html at all helpful? (TAME refers to Tense, Aspect, Mood and Evidentiality.)

> The `cop` relation should only be used for pure copulas that add at most TAME categories to the meaning of the predicate, which means that most languages have at most one copula, and only when the nonverbal predicate is treated as the head of the clause.

I would lean towards treating _'gyur_ and _song_ as main verbs if they (can) have a sense of becoming and are therefore not "pure". But this could be a tricky call.

**Comment by heacu** [comment]
Samyo - are you okay with the main verb analysis of these cases?

**Comment by samyorode** [comment]
For now, I am okay with it. Let’ see what will come up in future!

Am 17.10.2017 um 10:07 schrieb torma <notifications@github.com<mailto:notifications@github.com>>:


Samyo - are you okay with the main verb analysis of these cases?
