### ISSUE TITLE
Verbal compounds with adverbs?

### ISSUE THREAD

**Issue by solmsdorf** [tibetan-nlp/annotation-docs#12]
How do we deal with adverb-verb compounds, i. e. any compound with _kun tu_, _kun nas_, _nges par_, _mngon par_, _mchog tu_, _rjes su_, _nye bar_, _rnam par_, _yang dag par_, _yongs su_, _rab tu_, _legs par_, _shin tu_, _so sor_, _lhag par_, and the like?

Some of these are derived from verbs and marked as such with POS tags. However, they clearly function as adverbs, either altering the meaning of the main verb or—especially in canonical literature translated from Sanskrit where they represent verbal prefixes like _anu-_, _abhi-_, _pra-_, _prati-_, etc. pp.—without changing the core meaning of the verb. Preferably, we would draw `advmod` relations from the verb to the adverb; however, since the adverbs are not identified as such in the POS tagging, it is not possible to do so.

E. g. Mila 12b: _rje btsun mthu dang ser ba slob pa'i nye bar len pa_

=> Many more examples will come up in _mDzangs blun_

**Comment by heacu** [comment]
This is a case where the POS tag was chosen for etymological reasons but is misleading in terms of grammatical function. Your suggestion for how to correct this in the dependency makes sense: I've expanded the `advmod` relation to allow `VERB` targets. Since a `VERB` in this case won't have any argument structure, there is nothing else that you need to do.

I'll keep this issue open until I've made a note in the documentation.

**Comment by samyorode** [comment]
We also need to link verbs to adverbs that do not derive from verbs, e. g. _so sor gyes pa_; _phyir log_

**Comment by heacu** [comment]
I'm having second thoughts about this proposal. The UD guidelines state that [`advmod`](http://universaldependencies.org/u/dep/advmod.html) should be reserved for adverbs, and that [`obl`](http://universaldependencies.org/u/dep/obl.html) should be used for noun phrases and adpositional phrases which function adverbially. In other words, adverbial function is not sufficient to make something an `advmod`. But if this is the case, then it seems that the proposal won't work, unless _nye bar_ is reanalyzed as being one word with the part-of-speech `ADV`. So we must mark _nye ba_ as `obl`.

Would there be any mileage in using a sub-typed `obl:adv` relation? If we could reliably distinguish between plain `obl` (and not `obl:arg`) and `obl:adv`, then I could see the value.

What do you think?

**Comment by heacu** [comment]
To elaborate, at first I just thought we were finding a way to mark a relation from `VERB` to `VERB` where `advcl` wasn't appropriate. But I do not like the slippery slope to _so sor_, where _so so_ is clearly nominal and so shouldn't be linked as `advmod`. 

True, we are calling _nye ba_ in _nye bar_ a `VERB`, but we could equally have called it a `NOUN`, and indeed it shares case markers with nominals. In fact, the only reason for tagging verbal nouns `VERB` rather than `NOUN` that we are doing a project on verbs and it made it easier to track the verbs without relying on features, especially prior to lemmatisation. (Perhaps, however, this decision should be looked at.)

This is just a long way of saying that _nye bar_ is like _so sor_. Syntactically they have nominal case marking and so should be considered obliques.

**Comment by heacu** [comment]
Shall I search the annotated corpus and replace all instances of `advmod` with `obl:adv` where the the dependent is a verbal noun?

**Comment by solmsdorf** [comment]
Just to get it right:

· We will still be using `advmod` for adverbs which are already tagged as such.
· For adverb-verb compounds with _nye bar_, _so sor_, and the like, we will be using `obl:adv` from now on.

Right?

If so, no objections against `obl:adv`; go ahead, please replace `advmod` with `obl:adv` in the respective instances.

**Comment by heacu** [comment]
Where possible, we will follow the UD guidelines, using custom subtypes when we wish to supply additional information.

- You will use [`advmod`](http://universaldependencies.org/u/dep/advmod.html) for adverbs which are already tagged with the POS tag `ADV`.

- You  will use `obl:adv` for verbal nouns in adverbial function. I have identified three of these and replaced `advmod` with `obl:adv`: _rgyas par zhu_ (Mila 011a:T264), _nye bar lan_ (Mila 012b:T1201), and _rgyas par zhus_ (Mila 015a:T3120).

- You will use the [`compound`](http://universaldependencies.org/u/dep/compound.html) relation for VERB-VERB compounds. There are four examples of this so far. In all but one (Mila 013b:T1822), the first verb is _log_ (Mila 014b:T2565, 014b:T2757, 015a:T2853, 015a:T2952). I have replaced `advmod` with `compound` in these cases and made the `compound` relation an available linkage between two verbs.

**Comment by heacu** [comment]
There is one case, however, that still needs to be considered: VERB-SCONJ-VERB - for example, _phul du phyin pa_ (Mila 014b:T2468). How should we tag this?

**Comment by heacu** [comment]
@nikolaisolmsdorf or @samyorode can you look at one of the VERB-VERB compounds, namely _'phral dgos_ (Mila 013b:T1822)? _'phral_ is shown as a Nonverb lemma. What do you think about this example?

**Comment by samyorode** [comment]
As for _phul du phyin pa_: This is an adjective here, which is clear from the `ind` _cig_. _phul_ has to be understood as `N`, not as `V`, so "the magical power (_mthu_) has reached (_phyin pa_) the highest degree/perfection (_phul_), i.e. is excellent." I suggest to annotate _phul_ as `obl: arg`. What do you think?

**Comment by solmsdorf** [comment]
Concerning _’phral dgos_: _’phral_ clearly is short for _’phral du_, "immediate, at once", and should be tagged as `AV`. The relation from _dgos_ thus should definitely be `advmod`.

**Comment by heacu** [comment]
ok, i defer to you all including @nh36 on _'phral dgos_ (at first line of http://178.62.106.226/~badw/#/mila/013b). the proposal is to change the POS tag of _'phral_ from `VERB` to `ADV`... with my apologies the BRAT notes are still not automatically going to slack or anywhere else yet.

**Comment by heacu** [comment]
re _phul du phyin pa_ (first line of http://178.62.106.226/~badw/#/mila/014b), proposal above is to change POS tag of _phul_ from `VERB` to `NOUN`. what do you think @nh36 ?
if you want it to be an argument @samyorode then you could also do so by linking to the verb as `argcl`, w/o changing its POS category. but `obl:arg` is not an option for `VERB`.

**Comment by nh36** [comment]
I am not sure about 'phral. it depends on how we understand 'phral in 'phral du. Is 'phral in 'phral du a noun? If so, then it makes sense to treat 'phral alone as an adverb. But if 'phral is not in the lexicon as a verb, then this means that seeing 'phral du as an oblique NP is probably right so seeing 'phral in isolation as an adverb is probably right. How do we propose to translate  'phral dgos? I would usually expect to see dgos come after a main verb. Are we sure 'phral dgos doesn't mean 'need to separate'?

As for phul du phyin pa, in isolation I would understand it as 'came to give', in which case phul is definitely a verb, but if it means "the magical power (mthu) has reached (phyin pa) the highest degree/perfection (phul), i.e. is excellent.", then there is no problem changing phul into a noun (and du into a case marker). @torma @samyorode

**Comment by heacu** [comment]
In that case @samyorode, you can use the BRAT UI to change the POS categories of _phul_ and _du_, allowing _phul_ to be linked to the verb as `obl:arg`. Please also make sure to remove the normalization reference to Hill.

**Comment by heacu** [comment]
Just inserting this conclusion also from slack for the record: we are removing `advmod` and `advcl` from the list of relations that humans are asked to hand-annotate.

**Comment by solmsdorf** [comment]
@nh36 _’phral dgos_ may very well be rendered with "need to separate", in this context (Mila 13b), however, I would lean towards Quintman's interpretation and translation, i. e. "immediate needs":

_tshos tang (r. ltang) gnyis bur tang (r. ltang) gnyis khugs ’dug pa’i bur tang (r. ltang) gnyis ’phral dgos la spyad nas_

"She also obtained two bundles of dye and two packs of dried molasses, of which the two packs of dried molasses were used for our immediate needs"

**Comment by heacu** [comment]
@nikolaisolmsdorf in that case i take it that you are able to change the POS category of _'phral_ and remove the `compound` relation? thanks

**Comment by nh36** [comment]
It looks to me like Quintman is taking ’phral dgos 'immediate-need' as a noun. Incidentally, I have the Bacot and Lhalungpa translations which I can share if you want.

**Comment by heacu** [comment]
@nh36 if you feel comfortable doing so, you could share those translations to the Google Drive folder AHRC Lexicography in Motion > Corpus > Life of Milarepa which I just shared with you.

**Comment by solmsdorf** [comment]
Ok, once the need of the _compound_ relation is decided upon the issue can be closed, right?

@nh36 Many thanks, yes, please go ahead and upload the other translations to the shared Google Drive.

**Comment by nh36** [comment]
I have uploaded the translations.

**Comment by heacu** [comment]
I copy in some additional examples of `compound` reported by @nikolaisolmsdorf in slack, both from Mila 15b:

_nga la mthu gza’ gdong dmar nag zhes bya ba hūṃ shi dang phaṭ ’gyel thongs pa gcig yod pa_
> I possess a black magic rite called Zadong Marnak (Dark Red Faced Dza) that, when cast, kills with the syllable hūṃ and causes unconsciousness with the syllable phaṭ. (Quintman, p. 55)

_khong la ser ba ’dzub khrid thongs pa gcig ’dug pa_
> He possesses the practice of casting hailstorms by pointing one’s finger. (ibid.)

Butt (2010:49) defines a *complex predicate* as:

> a construction that involves two or more predicational elements 
> (such as nouns, verbs, and adjectives) which predicate as a single unit,
> i.e. their arguments map onto a monoclausal syntactic structure.

In contrast auxiliaries contribute merely TAME (tense, aspect, mood, evidentiality).

I will therefore close this issue and gradually build the case in the documentation for treating all of these examples as V-V "compounds". We shall erect a difficult to climb fence around the class of auxiliaries.
