### ISSUE TITLE
Causativization

### ISSUE THREAD

**Issue by solmsdorf** [tibetan-nlp/annotation-docs#2]
What is the proper UD relation between verb and aux for causative constructions (with _'jug_, _byed_, _mdzad_ etc.), argcl, aux, obj (like a light verb construction?)? 
E. g. (Mil p. 11a): 
· _ma smad nor slongs byed_ 
· _pha shul bus 'dzin du 'jug_

**Comment by heacu** [comment]
If I understand the construction correctly, then a causative would have the argument structure `arg1, argcl`. It licenses the causer, so that is its subject. And it subordinates another verb, which has to be an `argcl` in our scheme. Does this work?

**Comment by heacu** [comment]
If the causative verb were made to depend on the main verb by the `aux` relation, then the expanded valency would be a feature of the verb. This seems to me peculiar since it is the causative that is affecting the valence change.
