### ISSUE TITLE
Can 'yod' be a light verb?

### ISSUE THREAD

**Issue by samyorode** [tibetan-nlp/annotation-docs#3]
In Mila 11a there are examples of 'yod' that seem to be light verb or aux constructions: 

1. _zhal chems kyi yi ge rgyus yod pa_ "[they] had knowledge of/knew (tib. _rgyus yod_) the written testament." From the Tibetan perspective: _zhal chems kyi yi ge_ `arg2` _rgyus_ `arg1` _yod pa_ `Vn` "knowledge (arg1) of the testament (arg2) exists (Vn) [with the people] (`obl`, missing)". 

2. _zhal chems gsungs pa rgyus yod kyi mi bgres pa_ "the old people who had knowledge of the testament that was spoken." Tibetan: _zhal chems (arg2) gsungs pa rgyus (arg1) yod (V) kyi mi bgres pa (`obl`, preceded with Gen. kyi and therefore missing la?)_ "knowledge (arg1) of the testament (arg2) exists (V) with the old people."

Usually 'yod' should be a 1 place verb (as existential verb: "something exists"), right? Or can 'yod' be a light verb requiring 2 arguments?
Another example from rGyal rab gsal ba'i me long clarifies the missing `obl` from (1): _tsan dan sbrul gyi snying po (arg2) nga la (obl.) rgyus (arg1) yod pas (Vn)_ "because I have knowledge of/know the _tsan dan sbrul gyi snying po_ [wood]", literally: because knowledge of the ... wood exists with me.

This shows that there are two "senses" of 'yod': 1. yod "to exist" requiring 1 argument, and 2. yod as light verb or aux requiring 2 arguments.
Is that a possible approach to the _yod_ dilemma? Regarding the last example from rGyal rab gsal ba'i me long one could also argue that 'yod' is still a 1 place existential verb with 2 `obl` with the first _... snying po_ missing the la marker?!

**Comment by heacu** [comment]
Since all three examples given above have a potential `arg2` without case marking, I'd suggest not opting for the `obl` analysis unless there is really strong evidence for a missing _la_. I think your light verb analysis is preferable. So _yod_ has two senses.

**Comment by heacu** [comment]
See https://tibetan-nlp.github.io/lim-annodoc/#special-cases

**Comment by heacu** [comment]
If we are considering these light verb constructions, then it now follows that we need a new relation `arg1:lvc` to label nouns like _rgyus_.
