### ISSUE TITLE
Oblique relation without 'la'-case?

### ISSUE THREAD

**Issue by solmsdorf** [tibetan-nlp/annotation-docs#6]
In the following example an unmarked third argument of a verb is introduced, _la_ is expected but not present. Should we reintroduce `arg3`for these cases?

E. g. Mila 12a: _nged ma smad (`obl`=`arg3`) a khu dang a nes (`arg1`) gsha' ma  (`arg2`) rang ma bcol (V)_ "uncle and aunt did not return to us, mother and children, what was rightfully ours"

**Comment by heacu** [comment]
This example has been updated on Mila 12a and included in the documentation here: https://tibetan-nlp.github.io/lim-annodoc/#arg1-arg2-arg3
